import {fresh,suggested,uid,validate,rank,contextFor,calculate,command,help,briefing,reviewCard,calendar,encrypt,decrypt} from './core.js';
import {openStore,write,legacyMemories} from './store.js';
import {Voice} from './voice.js';
const $=id=>document.getElementById(id), el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let state,pending=null,toastTimer,recordURL,busy=false,wakeLock=null,requestController=null,chatEpoch=0;
const notify=text=>{clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4500);};
const failure=e=>{$('notice').textContent=e.message||String(e);$('notice').hidden=false;};
const guard=fn=>async(...args)=>{try{return await fn(...args);}catch(e){failure(e);}};
const click=(id,fn)=>$(id).addEventListener('click',guard(fn));
const submit=(id,fn)=>$(id).addEventListener('submit',guard(async e=>{e.preventDefault();await fn(e);}));
const action=(text,fn,cls='text-button')=>{const b=el('button',text,cls);b.type='button';b.onclick=guard(fn);return b;};
async function persist(){try{await write(structuredClone(state));}catch(e){throw Error('Could not save to device. Export a backup now. '+e.message);}}
function openTab(name){if(!$(name)?.classList.contains('view'))name='home';for(const s of document.querySelectorAll('.view'))s.hidden=s.id!==name;for(const b of document.querySelectorAll('.nav')){const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');}$('title').textContent=({home:'Command center',today:'Today',memory:'Memory',notes:'Notes',study:'Study',profile:'My profile',settings:'Settings & voice'})[name];history.replaceState(null,'','#'+name);}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>openTab(b.dataset.tab);window.onhashchange=()=>openTab(location.hash.slice(1));
const voice=new Voice({onText:text=>{$('chat-input').value=text;openTab('home');$('chat-input').focus();notify('Review your words, then tap Send.');},onState:text=>{$('voice-status').textContent=text;$('orb').classList.toggle('active',text.startsWith('Listening')||text==='Speaking');},onError:failure});
function talk(text){voice.speak(text,{...state.settings,language:state.profile.language});}
function addMessage(role,text){state.chats.push({id:uid(),role,text,created:Date.now()});state.chats=state.chats.slice(-200);renderChat();}
function renderChat(){const box=$('messages');box.replaceChildren();if(!state.chats.length)box.append(el('div','Start with /brief, save a memory, or ask what Jarvis knows about you. Your conversation stays on this device.','empty'));for(const m of state.chats){const row=el('div',undefined,'message '+m.role);row.append(el('span',m.role==='user'?'YOU':m.role==='system'?'SYSTEM':'JARVIS','role'),document.createTextNode(m.text));if(m.role==='assistant'){const tools=el('div',undefined,'message-tools');tools.append(action('Read aloud',()=>talk(m.text)),action('Save as memory',()=>{openTab('memory');$('memory-text').value=m.text.slice(0,1000);$('memory-private').checked=true;notify('Review and save this memory.');}),action('Copy',async()=>{await navigator.clipboard.writeText(m.text);notify('Copied.');}));row.append(tools);}box.append(row);}box.scrollTop=box.scrollHeight;}
function showProposal(kind,text){pending={kind,text};const box=$('proposal');box.hidden=false;box.replaceChildren(el('div',`Save this ${kind}? ${text}`));box.append(action('Save',async()=>{const p=pending;if(!p)return;pending=null;const now=Date.now();if(p.kind==='memory')state.memories.push({id:uid(),text:p.text.slice(0,1000),category:'Personal',private:true,pinned:false,updated:now});if(p.kind==='task')state.tasks.push({id:uid(),text:p.text.slice(0,500),done:false,created:now});if(p.kind==='note')state.notes.push({id:uid(),title:p.text.slice(0,70),body:p.text.slice(0,20000),updated:now});await persist();box.hidden=true;renderAll();notify('Saved to this device.');},'primary'),action('Cancel',()=>{pending=null;box.hidden=true;},'secondary'));}
async function send(text){if(busy||!text.trim())return;const epoch=chatEpoch;busy=true;$('send').disabled=true;try{
 const prior=state.chats.filter(m=>m.role!=='system').slice(-8).map(m=>({role:m.role,content:m.text}));addMessage('user',text);$('chat-input').value='';pending=null;$('proposal').hidden=true;const cmd=command(text);let answer;
 if(cmd){if(['memory','task','note'].includes(cmd.kind)){showProposal(cmd.kind,cmd.text);answer='Review the save request below.';}else if(cmd.kind==='calc')answer=String(calculate(cmd.text));else if(cmd.kind==='find'){const found=rank(state.memories,cmd.text);answer=found.length?found.map(x=>'• '+x.text).join('\n'):'No related saved memories.';}else if(cmd.kind==='brief')answer=briefing(state);else if(cmd.kind==='profile')answer=Object.entries(state.profile).filter(([k,v])=>v&&k!=='language').map(([k,v])=>k+': '+v).join('\n')||'Your profile is empty. Fill it in My profile.';else answer=help;}
 else if(state.settings.model){const context=contextFor(state,text);$('context-preview').textContent=context.length?`Sending ${context.length} approved profile/memory context entries to your local AI. Private memories and notes excluded.`:'No saved profile or memories sent.';requestController=new AbortController();const timeout=setTimeout(()=>requestController?.abort(),95000);try{const r=await fetch('./api/chat',{method:'POST',headers:{'Content-Type':'application/json','x-jarvis-access':sessionStorage.getItem('jarvis-access')||''},body:JSON.stringify({message:text,context,history:prior}),signal:requestController.signal});if(!(r.headers.get('content-type')||'').includes('application/json'))throw Error('No local AI backend at this address.');const data=await r.json();if(!r.ok)throw Error(data.error);answer=data.reply;}finally{clearTimeout(timeout);requestController=null;}}
 else{const matches=rank(state.memories,text,3);answer=matches.length?'Related saved memories:\n'+matches.map(x=>'• '+x.text).join('\n'):'I can search your saved facts and run local tools. Use /help for commands. Open-ended AI answers need a local model enabled in Settings.';}
 if(epoch!==chatEpoch)return;addMessage('assistant',answer);await persist();if(state.settings.speak)talk(answer);
 }catch(e){if(epoch!==chatEpoch)return;addMessage('system',e.name==='AbortError'?'AI request stopped.':e.message);await persist();}finally{busy=false;$('send').disabled=false;}}
submit('chat-form',()=>send($('chat-input').value.trim()));
for(const b of document.querySelectorAll('[data-action]'))b.onclick=guard(async()=>{addMessage('assistant',b.dataset.action==='brief'?briefing(state):help);await persist();openTab('home');});
click('dictate',()=>voice.listen(state.profile.language));click('stop-voice',()=>voice.stop());
click('chat-clear',async()=>{if(!confirm('Clear the conversation stored on this device?'))return;chatEpoch++;requestController?.abort();state.chats=[];await persist();renderChat();});
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
click('chat-export',()=>download('jarvis-conversation.txt',state.chats.map(m=>m.role.toUpperCase()+': '+m.text).join('\n\n'),'text/plain'));
function renderTasks(){const mode=$('task-filter').value;const list=$('task-list');list.replaceChildren();const tasks=state.tasks.filter(t=>mode==='all'||(mode==='done'?t.done:!t.done)).sort((a,b)=>(a.due||Infinity)-(b.due||Infinity));for(const t of tasks){const row=el('div',undefined,'item'+(t.done?' done':'')),head=el('div',undefined,'item-head'),check=el('input');check.type='checkbox';check.checked=t.done;check.setAttribute('aria-label','Complete '+t.text);check.onchange=guard(async()=>{t.done=check.checked;await persist();renderTasks();});head.append(check,el('span',t.text,'item-title'));row.append(head);if(t.due)row.append(el('div',(t.due<Date.now()&&!t.done?'Overdue · ':'')+new Date(t.due).toLocaleString(),'meta'));const buttons=el('div',undefined,'item-actions');buttons.append(action('Edit',async()=>{const text=prompt('Edit task',t.text);if(text?.trim()){t.text=text.trim().slice(0,500);await persist();renderTasks();}}),action('Delete',async()=>{if(confirm('Delete this task?')){state.tasks=state.tasks.filter(x=>x.id!==t.id);await persist();renderTasks();}},'text-button danger'));row.append(buttons);list.append(row);}if(!tasks.length)list.append(el('div','Nothing here yet. Add your next step.','empty'));$('metrics').replaceChildren();for(const [n,label]of [[state.tasks.filter(t=>!t.done).length,'Open tasks'],[state.tasks.filter(t=>t.done).length,'Completed'],[state.cards.filter(c=>(c.due||0)<=Date.now()).length,'Cards due']]){const m=el('div',undefined,'metric');m.append(el('b',String(n)),el('span',label));$('metrics').append(m);}}
submit('task-form',async()=>{const text=$('task-text').value.trim();if(!text)return;const raw=$('task-due').value,due=raw?new Date(raw).getTime():undefined;if(raw&&!Number.isFinite(due))throw Error('Choose a valid date.');state.tasks.push({id:uid(),text,done:false,...(due?{due}:{}),created:Date.now()});await persist();$('task-form').reset();renderTasks();notify('Task added.');});$('task-filter').onchange=renderTasks;
click('calendar-export',()=>{if(!state.tasks.some(t=>t.due&&!t.done))return notify('Add a date to an open task first.');download('jarvis-tasks.ics',calendar(state.tasks),'text/calendar');});
function resetMemory(){$('memory-form').reset();$('memory-id').value='';$('memory-private').checked=true;$('memory-save').textContent='Save memory';$('memory-cancel').hidden=true;}
function renderMemories(){const query=$('memory-search').value;const rows=query?rank(state.memories,query,100):[...state.memories].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updated-a.updated);$('memory-list').replaceChildren();for(const m of rows){const row=el('div',undefined,'item');row.append(el('div',m.text,'item-title'),el('div',[m.category,m.private?'Private':'Shareable',m.pinned?'Pinned':'',new Date(m.updated).toLocaleDateString()].filter(Boolean).join(' · '),'meta'));const buttons=el('div',undefined,'item-actions');buttons.append(action('Edit',()=>{$('memory-id').value=m.id;$('memory-text').value=m.text;$('memory-category').value=m.category;$('memory-private').checked=m.private;$('memory-pinned').checked=m.pinned;$('memory-save').textContent='Update memory';$('memory-cancel').hidden=false;$('memory-text').focus();}),action('Delete',async()=>{if(confirm('Delete this memory?')){state.memories=state.memories.filter(x=>x.id!==m.id);await persist();renderMemories();}},'text-button danger'));row.append(buttons);$('memory-list').append(row);}if(!rows.length)$('memory-list').append(el('div','No memories found. Add a fact above.','empty'));}
submit('memory-form',async()=>{const text=$('memory-text').value.trim();if(!text)return;const item={id:$('memory-id').value||uid(),text,category:$('memory-category').value,private:$('memory-private').checked,pinned:$('memory-pinned').checked,updated:Date.now()};const i=state.memories.findIndex(x=>x.id===item.id);if(i<0)state.memories.push(item);else state.memories[i]=item;await persist();resetMemory();renderMemories();notify('Memory saved.');});click('memory-cancel',resetMemory);$('memory-search').oninput=renderMemories;
click('legacy-import',async()=>{const old=await legacyMemories();let n=0;for(const m of old)if(typeof m.text==='string'&&!state.memories.some(x=>x.text===m.text)){state.memories.push({id:uid(),text:m.text.slice(0,1000),category:'Personal',private:true,pinned:false,updated:Date.now()});n++;}await persist();renderMemories();notify(n+' older memories imported as private.');});
function renderNotes(){const query=$('note-search').value.toLowerCase();$('note-list').replaceChildren();for(const n of [...state.notes].filter(n=>(n.title+' '+n.body).toLowerCase().includes(query)).sort((a,b)=>b.updated-a.updated)){const row=el('div',undefined,'item');row.append(el('div',n.title,'item-title'),el('div',n.body.slice(0,160),'subtle'));const buttons=el('div',undefined,'item-actions');buttons.append(action('Open',()=>{$('note-id').value=n.id;$('note-title').value=n.title;$('note-body').value=n.body;}),action('Delete',async()=>{if(confirm('Delete this note?')){state.notes=state.notes.filter(x=>x.id!==n.id);await persist();if($('note-id').value===n.id){$('note-form').reset();$('note-id').value='';}renderNotes();}},'text-button danger'));row.append(buttons);$('note-list').append(row);}if(!$('note-list').children.length)$('note-list').append(el('div','A blank page for your next idea.','empty'));}
submit('note-form',async()=>{const title=$('note-title').value.trim(),body=$('note-body').value.trim();if(!title||!body)return;const note={id:$('note-id').value||uid(),title,body,updated:Date.now()},i=state.notes.findIndex(n=>n.id===note.id);if(i<0)state.notes.push(note);else state.notes[i]=note;await persist();$('note-id').value=note.id;renderNotes();notify('Note saved.');});click('note-new',()=>{$('note-form').reset();$('note-id').value='';});$('note-search').oninput=renderNotes;click('notes-export',()=>download('jarvis-notes.md',state.notes.map(n=>'# '+n.title+'\n\n'+n.body).join('\n\n---\n\n'),'text/markdown'));
function renderStudy(){const due=state.cards.filter(c=>(c.due||0)<=Date.now()).sort((a,b)=>(a.due||0)-(b.due||0));$('review-count').textContent=due.length+' DUE';const box=$('review');box.replaceChildren();if(!due.length)box.append(el('div','Nothing due. Add a card below, or return when your next review is ready.','empty'));else{const c=due[0];box.append(el('div',c.question,'review-q'));box.append(action('Reveal answer',()=>{box.replaceChildren(el('div',c.question,'review-q'),el('div',c.answer,'review-a'));const row=el('div',undefined,'button-row');for(const [label,again]of [['Again in 10 min',true],['Got it',false]])row.append(action(label,async()=>{state.cards=state.cards.map(x=>x.id===c.id?reviewCard(c,again):x);await persist();renderStudy();renderTasks();},again?'secondary':'primary'));box.append(row);},'secondary space-top'));}$('card-list').replaceChildren();for(const c of state.cards){const row=el('div',undefined,'item');row.append(el('div',c.question,'item-title'),el('div','Next review: '+new Date(c.due||Date.now()).toLocaleString(),'meta'));row.append(action('Delete',async()=>{if(confirm('Delete this flashcard?')){state.cards=state.cards.filter(x=>x.id!==c.id);await persist();renderStudy();renderTasks();}},'text-button danger'));$('card-list').append(row);}$('focus-summary').textContent=state.focus.sessions.length+' sessions logged · '+Math.round(state.focus.sessions.reduce((n,x)=>n+x.ms,0)/60000)+' minutes total';}
submit('card-form',async()=>{const question=$('card-question').value.trim(),answer=$('card-answer').value.trim();if(!question||!answer)return;state.cards.push({id:uid(),question,answer,due:Date.now(),interval:0,updated:Date.now()});await persist();$('card-form').reset();renderStudy();renderTasks();notify('Flashcard added.');});
const elapsed=()=>state.focus.elapsed+(state.focus.started?Date.now()-state.focus.started:0);
function tick(){const sec=Math.floor(elapsed()/1000);$('focus-time').textContent=[Math.floor(sec/3600),Math.floor(sec/60)%60,sec%60].map(x=>String(x).padStart(2,'0')).join(':');$('focus-start').textContent=state.focus.started?'Pause focus':'Start focus';}
async function syncWake(){if(wakeLock){await wakeLock.release();wakeLock=null;}if($('wake-lock').checked&&state.focus.started&&!document.hidden){if(!navigator.wakeLock)return notify('Screen wake lock unavailable in this browser.');try{wakeLock=await navigator.wakeLock.request('screen');}catch{notify('Could not keep screen awake.');}}}
click('focus-start',async()=>{if(state.focus.started){state.focus.elapsed=elapsed();state.focus.started=null;}else state.focus.started=Date.now();await persist();tick();await syncWake();});click('focus-finish',async()=>{const ms=elapsed();if(ms>0)state.focus.sessions.push({date:Date.now(),ms});state.focus.sessions=state.focus.sessions.slice(-300);state.focus.elapsed=0;state.focus.started=null;await persist();tick();renderStudy();await syncWake();notify('Focus session logged.');});$('wake-lock').onchange=guard(syncWake);
function fillProfile(p){for(const k of Object.keys(state.profile))$('profile-'+k).value=p[k]||'';}
click('suggest-profile',()=>{fillProfile(suggested);notify('Review the suggestions, then save your profile.');});submit('profile-form',async()=>{for(const k of Object.keys(state.profile))state.profile[k]=$('profile-'+k).value.trim();await persist();renderIdentity();notify('Profile saved.');});
function renderIdentity(){$('greeting').textContent=state.profile.name?'Ready, '+state.profile.name+'.':'Ready when you are.';document.querySelector('.avatar').textContent=(state.profile.name||'Y')[0].toUpperCase();$('model-badge').textContent=state.settings.model?'LOCAL AI ENABLED':'LOCAL MODE';}
function fillVoices(){const select=$('voice-select');select.replaceChildren(el('option','System default'));select.options[0].value='';for(const v of window.speechSynthesis?.getVoices()||[]){const o=el('option',v.name+' · '+v.lang);o.value=v.voiceURI;select.append(o);}select.value=state.settings.voice;}
for(const[id,key,type]of [['speak-replies','speak','checked'],['voice-select','voice','value'],['voice-rate','rate','value'],['use-model','model','checked'],['share-context','share','checked']])$(id).onchange=guard(async()=>{state.settings[key]=key==='rate'?Number($(id)[type]):$(id)[type];await persist();renderIdentity();});
click('test-voice',()=>talk('Jarvis is ready. Let’s take one useful step.'));$('access-code').value=sessionStorage.getItem('jarvis-access')||'';$('access-code').onchange=()=>sessionStorage.setItem('jarvis-access',$('access-code').value);
click('check-server',async()=>{$('backend-status').textContent='Checking…';try{const r=await fetch('./api/status',{headers:{'x-jarvis-access':$('access-code').value},signal:AbortSignal.timeout(6000)});if(!(r.headers.get('content-type')||'').includes('application/json'))throw Error('Static app only; no AI backend.');const data=await r.json();if(!r.ok)throw Error(data.error);$('backend-status').textContent=data.configured?'Configured: '+data.model+' (test with a chat)':'Personal tools ready; no model configured.';}catch(e){$('backend-status').textContent=e.message;}});
function renderRecording(){if(recordURL)URL.revokeObjectURL(recordURL);const audio=$('voice-reference');audio.hidden=!state.voiceSample;if(state.voiceSample){recordURL=URL.createObjectURL(state.voiceSample);audio.src=recordURL;$('record-status').textContent='Reference saved only on this device.';}else{audio.removeAttribute('src');$('record-status').textContent='No voice reference saved.';}}
click('record-voice',async()=>{const b=$('record-voice');b.disabled=true;try{if(voice.recording){const blob=await voice.finish();if(blob&&blob.size<8*1024*1024){state.voiceSample=blob;await persist();renderRecording();}else throw Error('Recording too large; keep it under 30 seconds.');b.textContent='Record reference';}else{await voice.record();b.textContent='Save recording';}}finally{b.disabled=false;}});
click('delete-voice',async()=>{if(!state.voiceSample)return;if(confirm('Delete your local voice recording?')){state.voiceSample=null;await persist();renderRecording();}});
click('backup-export',async()=>{const copy=validate({...state,focus:{...state.focus,elapsed:elapsed()}});const result=await encrypt(copy,$('backup-password').value);download('jarvis-encrypted-backup.json',JSON.stringify(result));$('backup-password').value='';notify('Encrypted backup exported. Keep the password separately.');});
$('backup-import').onchange=guard(async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('Backup exceeds 10 MB.');const raw=JSON.parse(await file.text());const restored=validate(raw.format?await decrypt(raw,$('backup-password').value):raw);if(!confirm('Replace profile, chats, tasks, notes and memories with this backup? Your current voice reference will be deleted.'))return;voice.dispose();chatEpoch++;requestController?.abort();state=restored;await persist();location.reload();}finally{e.target.value='';}});
click('request-storage',async()=>{const ok=await navigator.storage?.persist?.();notify(ok?'Persistent storage granted. Keep backups too.':'Safari manages storage availability; keep regular backups.');await storageInfo();});async function storageInfo(){if(navigator.storage?.estimate){const d=await navigator.storage.estimate();$('storage-info').textContent='This origin uses about '+((d.usage||0)/1048576).toFixed(2)+' MB. Backups include profile, memories, notes, tasks, cards and chat.';}}
click('erase-data',async()=>{if(!confirm('Erase ALL Jarvis local data, including voice reference and v1 memories? Export a backup first.'))return;voice.dispose();chatEpoch++;requestController?.abort();state=fresh();await persist();await new Promise((resolve,reject)=>{const req=indexedDB.deleteDatabase('jarvis-memory-v1');req.onsuccess=resolve;req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Close other Jarvis tabs to erase v1 data.'));});sessionStorage.removeItem('jarvis-access');location.reload();});
function renderAll(){renderIdentity();renderChat();renderTasks();renderMemories();renderNotes();renderStudy();}
document.addEventListener('visibilitychange',()=>{if(document.hidden){voice.dispose();$('record-voice').textContent='Record reference';}syncWake().catch(failure);});window.addEventListener('pagehide',()=>voice.dispose());
try{state=await openStore();renderAll();fillProfile(state.profile);fillVoices();if(window.speechSynthesis)speechSynthesis.onvoiceschanged=fillVoices;for(const[id,key,type]of [['speak-replies','speak','checked'],['voice-rate','rate','value'],['use-model','model','checked'],['share-context','share','checked']])$(id)[type]=state.settings[key];renderRecording();tick();setInterval(tick,1000);$('date').textContent=new Date().toLocaleDateString([],{weekday:'short',day:'numeric',month:'short'});openTab(location.hash.slice(1)||'home');storageInfo().catch(()=>{});if(!voice.available())$('dictate').textContent='Use keyboard microphone';const network=()=>$('network').textContent=navigator.onLine?'On-device workspace':'Offline · local tools ready';network();window.addEventListener('online',network);window.addEventListener('offline',network);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>notify('Offline installation unavailable at this address.'));}catch(e){failure(Error('Device storage unavailable. Open in Safari with storage enabled. '+e.message));document.querySelectorAll('button,input,textarea').forEach(n=>n.disabled=true);}
