import {test}from'node:test';import assert from'node:assert/strict';
import{fresh,validate,rank,contextFor,calculate,command,reviewCard,calendar,encrypt,decrypt}from'../public/core.js';
test('calculator obeys precedence and rejects code and invalid input',()=>{assert.equal(calculate('-(3 + 2) * 4 + 9/3'),-17);assert.equal(calculate('0.1+0.2'),.3);for(const x of ['alert(1)','1/0','1+','(2','1..2','2 3','2**3']){assert.throws(()=>calculate(x));}});
test('semantic-lite recall and private/pinned context filtering',()=>{const s=fresh();s.profile.name='Yuvraaj';s.memories=[{id:'a',text:'My mathematics goal is the olympiad',private:false},{id:'b',text:'My secret maths goal',private:true,pinned:true},{id:'c',text:'I prefer hints',private:false,pinned:true}];assert.equal(rank(s.memories,'ioqm')[0].id,'a');assert.deepEqual(contextFor(s,'ioqm'),[]);s.settings.share=true;const ctx=contextFor(s,'ioqm').join(' ');assert.match(ctx,/Yuvraaj/);assert.match(ctx,/prefer hints/);assert.doesNotMatch(ctx,/secret/);});
test('commands identify proposals without executing mutation',()=>{assert.deepEqual(command('remember that I like hints'),{kind:'memory',text:'I like hints'});assert.deepEqual(command('add a task: study geometry'),{kind:'task',text:'study geometry'});assert.equal(command('Why does a hydraulic jump form?'),null);});
test('review schedules persist review intervals and retry delay',()=>{const card={id:'1',interval:0};assert.equal(reviewCard(card,true,100).due,600100);const next=reviewCard(card,false,100);assert.equal(next.interval,1);assert.equal(reviewCard(next,false,100).interval,2);});
test('backup validation excludes recording, checks corruption and resumes focus safely',()=>{const s=fresh();s.voiceSample='sensitive';s.focus.started=Date.now();const restored=validate(s);assert.equal(restored.voiceSample,null);assert.equal(restored.focus.started,null);assert.throws(()=>validate({...s,version:1}));assert.throws(()=>validate({...s,tasks:[{id:'x',text:5}]}));assert.throws(()=>validate({...s,memories:[{id:'x',text:'x',category:'a'},{id:'x',text:'y',category:'a'}]}));});
test('encrypted backup round trip and wrong-password rejection',async()=>{const s=fresh();s.profile.name='Yuvraaj';const data=await encrypt(s,'a-long-test-password');assert.ok(!JSON.stringify(data).includes('Yuvraaj'));assert.equal((await decrypt(data,'a-long-test-password')).profile.name,'Yuvraaj');await assert.rejects(()=>decrypt(data,'wrong-password'));});
test('calendar exports only dated incomplete tasks and escapes data',()=>{const ics=calendar([{id:'1',text:'Maths, proofs;\nReview',due:1750000000000},{id:'2',text:'Done',due:1750000000000,done:true},{id:'3',text:'No date'}]);assert.match(ics,/DTSTART:20250615T150640Z/);assert.match(ics,/Maths\\, proofs\\;\\nReview/);assert.doesNotMatch(ics,/No date|SUMMARY:Done/);});
