export const uid=()=>crypto.randomUUID();
export const fresh=()=>({version:2,profile:{name:'',alias:'',language:'en-IN',goals:'',interests:'',preferences:'',projects:''},memories:[],tasks:[],notes:[],cards:[],chats:[],focus:{started:null,elapsed:0,sessions:[]},settings:{speak:false,voice:'',rate:1,model:false,share:false},voiceSample:null});
export const suggested={name:'Yuvraaj',alias:'Yuvix',language:'en-IN',goals:'Prepare for maths olympiads, especially IOQM and RMO. Explore quantum science and computing.',interests:'Mathematics, theoretical physics, programming, Arduino and creative projects.',preferences:'English or Hinglish. Start with a small hint for maths. Clear, practical explanations.',projects:'Jarvis personal assistant; Madhukunj website; game development.'};
export function validate(s){
 if(!s||s.version!==2||!s.profile||!s.settings||!s.focus)throw Error('This is not a Jarvis v2 backup.');
 const copy=fresh();for(const k of Object.keys(copy.profile)){if(typeof s.profile[k]!=='string'||s.profile[k].length>3000)throw Error('Invalid profile.');copy.profile[k]=s.profile[k];}
 const specs={memories:['text','category'],tasks:['text'],notes:['title','body'],cards:['question','answer'],chats:['role','text']};
 for(const [name,keys]of Object.entries(specs)){
  if(!Array.isArray(s[name])||s[name].length>2000)throw Error('Invalid '+name);const ids=new Set();
  copy[name]=s[name].map(item=>{if(!item||typeof item.id!=='string'||ids.has(item.id)||keys.some(k=>typeof item[k]!=='string'||item[k].length>20000))throw Error('Invalid '+name+' entry.');ids.add(item.id);const out={id:item.id};for(const k of keys)out[k]=item[k];for(const k of ['updated','due','interval','created'])if(Number.isFinite(item[k]))out[k]=item[k];for(const k of ['pinned','private','done'])out[k]=!!item[k];if(name==='chats'&&!['user','assistant','system'].includes(out.role))throw Error('Invalid chat role');return out;});
 }
 copy.settings={speak:!!s.settings.speak,voice:typeof s.settings.voice==='string'?s.settings.voice.slice(0,500):'',rate:Math.max(.6,Math.min(1.5,Number(s.settings.rate)||1)),model:!!s.settings.model,share:!!s.settings.share};
 copy.focus={started:null,elapsed:Number.isFinite(s.focus.elapsed)?Math.max(0,s.focus.elapsed):0,sessions:Array.isArray(s.focus.sessions)?s.focus.sessions.filter(x=>Number.isFinite(x.date)&&Number.isFinite(x.ms)&&x.ms>=0).slice(-300):[]};
 // Voice recordings never travel in a backup.
 return copy;
}
const groups=[['math','maths','mathematics','olympiad','ioqm','rmo'],['programming','coding','code','javascript','python'],['school','class','study','studying','exam','revision','learn','learning'],['physics','quantum','science'],['food','bakery','sweets','madhukunj'],['ipad','tablet','ios','safari']];
const stop=new Set('the and for are what how my me is a an to of do i about can you tell'.split(' '));
export function vector(text){const v=new Map();for(const w of text.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]){if(stop.has(w)||w.length<2)continue;const g=groups.find(g=>g.includes(w)),k=g?'concept:'+g[0]:w;v.set(k,(v.get(k)||0)+1);for(let i=0;i<w.length-2;i++){const key='#'+w.slice(i,i+3);v.set(key,(v.get(key)||0)+.08);}}const n=Math.hypot(...v.values())||1;return new Map([...v].map(([k,x])=>[k,x/n]));}
export function rank(items,query,limit=5){const q=vector(query);return items.map(item=>{const v=vector(item.text||item.title+' '+item.body);let score=0;for(const[k,x]of q)score+=x*(v.get(k)||0);return{item,score};}).filter(x=>x.score>.1).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.item);}
export function contextFor(s,query){if(!s.settings.share)return[];const profile=Object.entries(s.profile).filter(([k,v])=>v&&k!=='language').map(([k,v])=>k+': '+v).join('\n');const pool=s.memories.filter(m=>!m.private);const pinned=pool.filter(m=>m.pinned).slice(0,2);const picked=[...pinned,...rank(pool,query,5)].filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i).slice(0,5);return [profile,...picked.map(m=>m.text)].filter(Boolean);}
// Safe recursive-descent calculator: no eval, Function or arbitrary code.
export function calculate(source){
 if(/\d\s+\d/.test(source))throw Error('Put an operator between numbers.');const s=source.replace(/×/g,'*').replace(/÷/g,'/').replace(/\s/g,'');if(s.length>200||!s||/[^\d.+\-*/()%]/.test(s))throw Error('Use numbers, + − * / % and parentheses.');
 const tokens=s.match(/\d*\.\d+|\d+\.?\d*|[()+\-*/%]/g)||[];if(tokens.join('')!==s)throw Error('Invalid expression');let i=0;
 const atom=()=>{const t=tokens[i++];if(t==='-')return-atom();if(t==='+')return atom();if(t==='('){const n=sum();if(tokens[i++]!==')')throw Error('Missing closing parenthesis');return n;}if(t===undefined||!/^(?:\d*\.\d+|\d+\.?\d*)$/.test(t))throw Error('Expected a number');return Number(t);};
 const term=()=>{let n=atom();while(['*','/','%'].includes(tokens[i])){const op=tokens[i++],b=atom();if(b===0&&op!=='*')throw Error('Cannot divide by zero');n=op==='*'?n*b:op==='/'?n/b:n%b;}return n;};
 const sum=()=>{let n=term();while(['+','-'].includes(tokens[i])){const op=tokens[i++],b=term();n=op==='+'?n+b:n-b;}return n;};const out=sum();if(i!==tokens.length||!Number.isFinite(out))throw Error('Invalid expression');return Number(out.toPrecision(12));
}
export function command(text){let m;const t=text.trim();if((m=t.match(/^(?:\/remember|remember(?: that)?)\s+(.+)/is)))return{kind:'memory',text:m[1]};if((m=t.match(/^(?:\/task|add (?:a )?task:?|remind me to)\s+(.+)/is)))return{kind:'task',text:m[1]};if((m=t.match(/^(?:\/note|take (?:a )?note:?)\s+(.+)/is)))return{kind:'note',text:m[1]};if((m=t.match(/^(?:\/find|find memories about)\s+(.+)/is)))return{kind:'find',text:m[1]};if((m=t.match(/^(?:\/calc|calculate)\s+(.+)/is)))return{kind:'calc',text:m[1]};if(/^(?:\/brief|my day|daily briefing)$/i.test(t))return{kind:'brief'};if(/^(?:\/help|help)$/i.test(t))return{kind:'help'};if(/^(?:\/profile|what do you know about me\??)$/i.test(t))return{kind:'profile'};return null;}
export const help='Local commands:\n/remember a fact\n/task something to do\n/note an idea\n/find maths\n/calc (12 + 3) * 4\n/brief\n/profile\n\nSaving through chat always asks you to approve. For open-ended AI answers, enable a local model in Settings.';
export function briefing(s){const due=s.cards.filter(c=>(c.due||0)<=Date.now()).length;return `${s.profile.name?'Hello, '+s.profile.name+'. ':''}${s.tasks.filter(t=>!t.done).length} open tasks · ${due} cards due.\n`+s.tasks.filter(t=>!t.done).slice(0,8).map(t=>'• '+t.text+(t.due?' — '+new Date(t.due).toLocaleDateString():'')).join('\n');}
export function reviewCard(card,again,now=Date.now()){const interval=again?0:(card.interval?Math.min(180,card.interval*2):1);return {...card,interval,due:now+(again?600000:interval*86400000),updated:now};}
const escapeICS=s=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\r/g,'');
const stamp=ms=>new Date(ms).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
export function calendar(tasks){return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Jarvis//Personal tasks//EN',...tasks.filter(t=>t.due&&!t.done).flatMap(t=>['BEGIN:VEVENT','UID:'+t.id+'@jarvis.local','DTSTAMP:'+stamp(Date.now()),'DTSTART:'+stamp(t.due),'DTEND:'+stamp(t.due+1800000),'SUMMARY:'+escapeICS(t.text),'END:VEVENT']),'END:VCALENDAR',''].join('\r\n');}
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s);}
function un64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function keyFor(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function encrypt(data,password){if(password.length<10)throw Error('Use a backup password of at least 10 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFor(password,salt);const content=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(data)));return{format:'jarvis-encrypted-v1',salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(content))};}
export async function decrypt(data,password){if(data.format!=='jarvis-encrypted-v1')throw Error('Unknown backup format');const key=await keyFor(password,un64(data.salt));try{const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(data.iv)},key,un64(data.data));return JSON.parse(new TextDecoder().decode(bytes));}catch{throw Error('Wrong password or damaged backup.');}}
