export class Voice {
 constructor({onText,onState,onError}){Object.assign(this,{onText,onState,onError});this.recognition=null;this.recording=null;}
 available(){return !!(window.SpeechRecognition||window.webkitSpeechRecognition);}
 listen(language){this.stop();const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API)throw Error('Browser dictation unavailable. Use the iPad keyboard microphone.');const r=new API();this.recognition=r;r.lang=language||'en-IN';r.interimResults=false;r.continuous=false;r.onresult=e=>{const text=Array.from(e.results).map(x=>x[0].transcript).join(' ');this.onText(text);};r.onerror=e=>{this.onError('Dictation: '+e.error+'. You can use the keyboard microphone instead.');};r.onend=()=>{this.recognition=null;this.onState('Ready');};r.start();this.onState('Listening — tap Stop to cancel');}
 speak(text,settings){if(!window.speechSynthesis)throw Error('Speech output unavailable.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.slice(0,3000));u.lang=settings.language||'en-IN';u.rate=settings.rate||1;u.voice=speechSynthesis.getVoices().find(v=>v.voiceURI===settings.voice)||null;u.onstart=()=>this.onState('Speaking');u.onend=()=>this.onState('Ready');u.onerror=()=>this.onState('Ready');speechSynthesis.speak(u);}
 stop(){this.recognition?.abort();this.recognition=null;window.speechSynthesis?.cancel();this.onState('Ready');}
 async record(){this.stop();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Voice reference needs HTTPS and a supported microphone.');this.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});this.chunks=[];this.recording=new MediaRecorder(this.stream);this.recording.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data);};this.recording.start();this.onState('Recording reference — tap Save recording');this.timeout=setTimeout(()=>this.onError('A 30-second reference is enough. Tap Save recording.'),30000);}
 finish(){return new Promise(resolve=>{if(!this.recording)return resolve(null);this.recording.onstop=()=>{const blob=new Blob(this.chunks,{type:this.recording.mimeType});this.stream.getTracks().forEach(t=>t.stop());clearTimeout(this.timeout);this.recording=null;this.onState('Ready');resolve(blob);};this.recording.stop();});}
 dispose(){this.stop();clearTimeout(this.timeout);if(this.recording){this.recording.ondataavailable=null;this.recording.onstop=null;this.recording.stop();this.recording=null;}this.stream?.getTracks().forEach(t=>t.stop());}
}
